---
# Tasks to ensure all the requisites are met to run this role
- name: Ensure powershell is installed with chocolatey
  # Content suggestion provided by Ansible Lightspeed
  chocolatey.chocolatey.win_chocolatey:
    name: powershell
    state: present
  register: _install_powershell

- name: Reboot the host if PowerShell-Windows-Server feature requires it
  # Content suggestion provided by Ansible Lightspeed
  ansible.windows.win_reboot:
  when:
    - _install_powershell is changed

- name: Ensure destination folder {{ mssql_package_dest }} exists
  # Content suggestion provided by Ansible Lightspeed
  ansible.windows.win_file:
    path: "{{ _path_ }}"
    state: directory

- name: Get package from Microsoft
  # Content suggestion provided by Ansible Lightspeed
  ansible.windows.win_get_url:
    url: "{{ mssql_package_url }}"
    dest: "{{ mssql_package_dest }}"
  register: _ms_download
  until: _ms_download is succeeded
  retries: 10
  delay: 5
