- name: Check updates as needed
  hosts: all

  tasks:
    - name: Check for all the security, critical, and rollup updates in the windows servers
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        state: searched
      register: wua_updates_result

    - name: Show updates result from previous task
      ansible.builtin.debug:
        var: wua_updates_result

